

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class LicenseAdditionalAttribute : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the LicenseAdditionalAttribute entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public LicenseAdditionalAttribute()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public LicenseAdditionalAttribute(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.LicenseAdditionalAttribute> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LicenseAdditionalAttribute_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LicenseAdditionalAttribute_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.GetValue(this, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.SetValue(this, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.GetValue(this, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.SetValue(this, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.GetValue(this, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.SetValue(this, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Value
        {
            get
            {
                return global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.GetValue(this, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties.Value);
            }
            set
            {
                global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.SetValue(this, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties.Value, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Value_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Value_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Value_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.License License
        {
            get
            {
                return global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.GetValue(this, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties.License);
            }
            set
            {
                global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.SetValue(this, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties.License, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void License_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void License_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void License_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.LicenseAdditionalAttribute,
                global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass,
                global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.IImplementation,
                global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass>.Entry
                __LicenseAdditionalAttributeEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass>.Entry(
                    global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.__LicenseAdditionalAttribute_CreateNew,
                    global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.__LicenseAdditionalAttribute_Created,
                    global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.__LicenseAdditionalAttribute_AllowSaveWithErrors);
            private static global::LightSwitchApplication.LicenseAdditionalAttribute __LicenseAdditionalAttribute_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.LicenseAdditionalAttribute> es)
            {
                return new global::LightSwitchApplication.LicenseAdditionalAttribute(es);
            }
            private static void __LicenseAdditionalAttribute_Created(global::LightSwitchApplication.LicenseAdditionalAttribute e)
            {
                e.LicenseAdditionalAttribute_Created();
            }
            private static bool __LicenseAdditionalAttribute_AllowSaveWithErrors(global::LightSwitchApplication.LicenseAdditionalAttribute e)
            {
                bool result = false;
                e.LicenseAdditionalAttribute_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, string> Value
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties.Value) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, global::LightSwitchApplication.License> License
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties.License) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, global::LightSwitchApplication.License>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new string Name { get; set; }
                new string Value { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation License { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, int>.Data> c, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.LicenseAdditionalAttribute e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.LicenseAdditionalAttribute e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.LicenseAdditionalAttribute e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.LicenseAdditionalAttribute e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.LicenseAdditionalAttribute e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.LicenseAdditionalAttribute e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, string>.Data> c, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.LicenseAdditionalAttribute e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.LicenseAdditionalAttribute e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.LicenseAdditionalAttribute e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, string>.Entry
                    Value = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, string>.Entry(
                        "Value",
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._Value_Stub,
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._Value_ComputeIsReadOnly,
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._Value_Validate,
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._Value_GetImplementationValue,
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._Value_SetImplementationValue,
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._Value_OnValueChanged);
                private static void _Value_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, string>.Data> c, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass d, object sf)
                {
                    c(d, ref d._Value, sf);
                }
                private static bool _Value_ComputeIsReadOnly(global::LightSwitchApplication.LicenseAdditionalAttribute e)
                {
                    bool result = false;
                    e.Value_IsReadOnly(ref result);
                    return result;
                }
                private static void _Value_Validate(global::LightSwitchApplication.LicenseAdditionalAttribute e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Value_Validate(r);
                }
                private static string _Value_GetImplementationValue(global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass d)
                {
                    return d.ImplementationEntity.Value;
                }
                private static void _Value_SetImplementationValue(global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Value = v;
                }
                private static void _Value_OnValueChanged(global::LightSwitchApplication.LicenseAdditionalAttribute e)
                {
                    e.Value_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, global::LightSwitchApplication.License>.Entry
                    License = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, global::LightSwitchApplication.License>.Entry(
                        "License",
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._License_Stub,
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._License_ComputeIsReadOnly,
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._License_Validate,
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._License_GetCoreImplementationValue,
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._License_GetImplementationValue,
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._License_SetImplementationValue,
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._License_Refresh,
                        global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties._License_OnValueChanged);
                private static void _License_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, global::LightSwitchApplication.License>.Data> c, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass d, object sf)
                {
                    c(d, ref d._License, sf);
                }
                private static bool _License_ComputeIsReadOnly(global::LightSwitchApplication.LicenseAdditionalAttribute e)
                {
                    bool result = false;
                    e.License_IsReadOnly(ref result);
                    return result;
                }
                private static void _License_Validate(global::LightSwitchApplication.LicenseAdditionalAttribute e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.License_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _License_GetCoreImplementationValue(global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass d)
                {
                    return d.ImplementationEntity.License;
                }
                private static global::LightSwitchApplication.License _License_GetImplementationValue(global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.License, global::LightSwitchApplication.License.DetailsClass>(global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties.License, ref d._License);
                }
                private static void _License_SetImplementationValue(global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass d, global::LightSwitchApplication.License v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties.License, ref d._License, (i, ev) => i.License = ev, v);
                }
                private static void _License_Refresh(global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass.PropertySetProperties.License, ref d._License);
                }
                private static void _License_OnValueChanged(global::LightSwitchApplication.LicenseAdditionalAttribute e)
                {
                    e.License_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, string>.Data _Value;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.LicenseAdditionalAttribute, global::LightSwitchApplication.LicenseAdditionalAttribute.DetailsClass, global::LightSwitchApplication.License>.Data _License;
            
        }
    
        #endregion
    }
    
    #endregion
}
